spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job-server?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Amgfaa289!@

  data:
    redis:
      host: localhost
      port: 6379


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testdisk1110@gmail.com
    password: "lcbk silq oexu laom"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  logging:
    level:
      org:
        springframework: DEBUG

jwt:
  secret: zWgYYrmkAWMHkMgjOlwV8bwO8FbNVWeJjKz9SR0M6GOBbPTb6G77mITLOXPGzFaaCTAE5CtYvGkzHzP5Aow9dA==
