spring:
  application:
    name: jobworld-server
  datasource:
    url: jdbc:mysql://${DB_HOST:job-world-db2.c9m4kwqu6stm.ap-northeast-2.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:job-world-db2}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:jhstl}
    password: ${DB_PASSWORD:amgfaa289}
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false
  data:
    redis:
      host: ${REDIS_HOST:13.125.112.86}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testdisk1110@gmail.com
    password: "lcbksilqoexulaom"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "http://13.125.112.86/job-world/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      resolve-lazily: false

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:job-world-profile-images}
    region:
      static: ap-northeast-2
    stack:
      auto: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    oauth2RedirectUrl: http://13.125.112.86/swagger-ui/oauth2-redirect.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  packages-to-scan: com.example.jobworldserver.auth.controller, com.example.jobworldserver.jobs.controller, com.example.jobworldserver.profile.controller

logging:
  file:
    name: /app/logs/jobworld-server.log
  level:
    root: INFO
    com.example.jobworldserver.auth.service.EmailService: DEBUG  # EmailService 디버그
    com.example.jobworldserver.auth.service.EmailVerificationService: DEBUG  # EmailVerificationService 디버그
    com.example.jobworldserver.auth.controller.AuthController: DEBUG  # AuthController 디버그
    org.springframework.mail: DEBUG  # Spring Mail 디버그
    com.sun.mail: DEBUG  # JavaMail 디버그
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    com.example.jobworldserver.domain.config: INFO
    com.zaxxer.hikari: DEBUG
    com.mysql.cj.jdbc: DEBUG
    org.springdoc: DEBUG

jwt:
  secret: ${JWT_SECRET:zWgYYrmkAWMHkMgjOlwV8bwO8FbNVWeJjKz9SR0M6GOBbPTb6G77mITLOXPGzFaaCTAE5CtYvGkzHzP5Aow9dA==}