spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:job-world-db2.c9m4kwqu6stm.ap-northeast-2.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:job-world-db2}?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:jhstl}
    password: ${DB_PASSWORD:amgfaa289}
  main:
    allow-bean-definition-overriding: false
    allow-circular-references: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: testdisk1110@gmail.com
    password: "lcbk silq oexu laom"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/job-world/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
logging:
  level:
    org.springframework.core.env: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    com.example.jobworldserver.domain.config: INFO
    com.zaxxer.hikari: DEBUG
    com.mysql.cj.jdbc: DEBUG

jwt:
  secret: ${JWT_SECRET:zWgYYrmkAWMHkMgjOlwV8bwO8FbNVWeJjKz9SR0M6GOBbPTb6G77mITLOXPGzFaaCTAE5CtYvGkzHzP5Aow9dA==}

file:
  storage:
    local:
      directory: ${FILE_STORAGE_DIRECTORY:${user.home}/Uploads}