name: Deploy to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: job-world-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
        id: build-image

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USER_NAME: ubuntu
        run: |
          echo "Private key file creation started"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key || { echo "Private key setup failed"; exit 1; }
          echo "SSH connection attempt to ${USER_NAME}@${HOSTNAME}"
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            echo "Logging into ECR on EC2"
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }} || { echo "ECR login failed"; exit 1; }
            echo "Pulling Docker image: ${{ steps.build-image.outputs.image }}"
            docker pull ${{ steps.build-image.outputs.image }} || { echo "Image pull failed"; exit 1; }
            echo "Stopping and removing old container"
            docker stop job-world-app || true
            docker rm job-world-app || true
            echo "Running new container"
            docker run -d --name job-world-app -p 8080:8080 \
              -e SPRING_DATASOURCE_URL="jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?useSSL=false&serverTimezone=UTC" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USER }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e SPRING_DATA_REDIS_HOST="${{ secrets.REDIS_HOST }}" \
              -e SPRING_DATA_REDIS_PORT="6379" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              -e AWS_S3_BUCKET="${{ secrets.AWS_S3_BUCKET }}" \
              ${{ steps.build-image.outputs.image }} || { echo "Container start failed"; exit 1; }
            echo "Deployment completed"
          ' || { echo "SSH connection failed"; exit 1; }
        shell: bash